name: rewards_portal
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloudinary_sdk: ^4.0.2+10
  cupertino_icons: ^1.0.2
  diamond_bottom_bar: ^1.0.0
  duration: ^3.0.11
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_inappwebview: ^5.4.3+7
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  flutter_social_textfield: ^0.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  image_picker: any
  jwt_decoder: ^2.0.1
  lit_relative_date_time: ^1.2.0
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
